name: app
description: "A new Flutter project."
publish_to: 'none'  # Prevents accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+2
  cupertino_icons: ^1.0.6
  file_picker: ^5.2.2
  path_provider: ^2.0.10
  share_plus: ^6.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
